"""Rendered file bodies for scaffold_web_face.py — qjango-shaped djapp.

`render_project` writes a Django ASGI `djapp/` tree, vertical-first: a
composition-root `project/` package, and one Django app per api vertical under
`apps/<name>/` that co-locates BOTH faces over that vertical's api:

  apps/<v>/commands.py        the transport-neutral binding over <pkg>.<v>.api
  apps/<v>/views/apiviews.py  REST views built from commands
  apps/<v>/views/mcpviews.py  MCP tool table built from commands
  apps/<v>/urls/apiurls.py    REST routes
  apps/mcp.py                 the single MCP endpoint, aggregating every mcpviews

Import DAG: commands -> <pkg>.<v>.api; apiviews/mcpviews -> commands; apiurls ->
{commands, apiviews}; apps/mcp.py -> apps/<v>/views/mcpviews; project -> apps;
nothing imports project. The two faces are siblings over `commands` (the binding
is the shared ancestor) -- mcp never imports the REST face. The binding lives in
exactly one place, so the bulky `input_schema` is written once per command, not
once per face. Database-light: empty models/admin, no qux.
"""

import json
from pathlib import Path

# --------------------------------------------------------------------------
# project/ — composition root (top of the import DAG)
# --------------------------------------------------------------------------

MANAGE_PY = '''#!/usr/bin/env python
# manage.py is the settings bootstrapper; pylint-django cannot see the runtime
# DJANGO_SETTINGS_MODULE, so its django-not-configured fires spuriously here.
# pylint: disable=django-not-configured
"""Django management entry (generated by racecar-deploy)."""
import os
import sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project.settings.api")
    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
'''

ASGI_PY = '''"""ASGI entry: `uvicorn project.asgi:application`. Each process picks its face
via DJANGO_SETTINGS_MODULE (project.settings.api | project.settings.mcp); the
default here is only a fallback for a bare launch."""
import os

from django.core.asgi import get_asgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project.settings.api")
application = get_asgi_application()
'''

WSGI_PY = '''"""WSGI entry (present for parity; the faces run under ASGI)."""
import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project.settings.api")
application = get_wsgi_application()
'''

FACEGUARD_PY = '''"""Per-face host guard. Keeps a host middleware without swapping the urlconf.

Each process serves exactly one face: its DJANGO_SETTINGS_MODULE
(project.settings.api | project.settings.mcp) fixes ROOT_URLCONF at boot. This
middleware attaches `request.face` and 404s a request whose host clearly belongs
to the other face. It never assigns `request.urlconf` -- face selection is
boot-time, per process, not per request.
"""
from django.conf import settings
from django.http import HttpResponseNotFound


class FaceHostMiddleware:
    """Attach request.face from settings.FACE; 404 a host bound to the other face."""

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        request.face = getattr(settings, "FACE", "api")
        host = request.get_host().split(":")[0]
        other_prefix = "mcp." if request.face == "api" else "api."
        if host.startswith(other_prefix):
            return HttpResponseNotFound(b"host does not match this face")
        return self.get_response(request)
'''

VIEWS_PY = '''"""Project-level views (api face): serve the generated OpenAPI document."""
import json

from django.conf import settings
from django.http import JsonResponse

_OPENAPI_PATH = settings.BASE_DIR / "docs" / "api" / "openapi.json"
try:
    _OPENAPI = json.loads(_OPENAPI_PATH.read_text())
except OSError:
    _OPENAPI = {}


def openapi(request):
    """Serve the generated OpenAPI 3.1 document (docs/api/openapi.json)."""
    return JsonResponse(_OPENAPI)
'''


def _settings_py(manifest: dict) -> str:
    apps_block = "\n".join(f'    "apps.{v["app"]}",' for v in manifest["verticals"])
    return f'''"""Shared base settings (racecar-deploy), house style. One process per face:
each vhost launches its own settings module (project.settings.api /
project.settings.mcp), and that module sets ROOT_URLCONF to its face's urlconf.
This base holds everything common; the face modules add only what differs.
Database-light (sqlite default, no domain models, no qux).

django_extensions is face-agnostic (no urls) and lives here; debug_toolbar is
api-only and is added in project.settings.api, because it mounts __debug__/ in
project.urls.api and would otherwise reverse `djdt` against a urlconf without it.

Install dev tools with `make install-dev` (the library `django` group);
`make install` installs the djapp runtime (django, uvicorn)."""
import os
from pathlib import Path

# settings.py -> settings/ -> project/ -> djapp root
BASE_DIR = Path(__file__).resolve().parent.parent.parent

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-insecure-deploy-key")
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"
ALLOWED_HOSTS = os.environ.get(
    "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,api.localhost,mcp.localhost"
).split(",")
USE_X_FORWARDED_HOST = os.environ.get("DJANGO_USE_X_FORWARDED_HOST", "1") == "1"
INTERNAL_IPS = ["127.0.0.1"]

# Dev tools, DEBUG-gated (the house DEBUG_APPS pattern). debug_toolbar is added
# per-face in project.settings.api, not here. Single assignment (no augmented +=)
# so pylint keeps INSTALLED_APPS a module constant.
DEBUG_APPS = ["django_extensions"]
INSTALLED_APPS = [
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    *(DEBUG_APPS if DEBUG else []),
{apps_block}
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "project.faceguard.FaceHostMiddleware",
]

# Default face + urlconf. project.settings.{{api,mcp}} override both per process;
# this default lets bare `project.settings.settings` (e.g. manage.py fallbacks)
# resolve urls.
FACE = "api"
ROOT_URLCONF = "project.urls.apiurls"
WSGI_APPLICATION = "project.wsgi.application"

TEMPLATES = [
    {{
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {{"context_processors": ["django.template.context_processors.request"]}},
    }}
]

# Database — the house pattern (xenocrates): sqlite (db.sqlite3) by default,
# mysql when DB_TYPE=mysql, env-driven. Database-light, but Django's machinery
# (migrations, sessions) needs a real ENGINE.
MYSQL_SETTINGS = {{
    "ENGINE": "django.db.backends.mysql",
    "NAME": os.getenv("DB_NAME", None),
    "USER": os.getenv("DB_USERNAME", None),
    "PASSWORD": os.getenv("DB_PASSWORD", None),
    "HOST": os.getenv("DB_HOST", "localhost"),
    "PORT": os.getenv("DB_PORT", ""),
    "OPTIONS": {{"charset": "utf8mb4", "ssl": {{"ca": os.getenv("DB_SSL_CERT", None)}}}},
}}
SQLITE_SETTINGS = {{
    "ENGINE": "django.db.backends.sqlite3",
    "NAME": BASE_DIR / "db.sqlite3",
}}
if os.getenv("DB_TYPE", "sqlite").lower() == "mysql":
    DATABASES = {{"default": MYSQL_SETTINGS}}
else:
    DATABASES = {{"default": SQLITE_SETTINGS}}

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"
USE_TZ = True
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Write verbs (any non-GET command) are refused unless this is enabled out of
# band. A no-tty face cannot prompt, so it fails safe.
RACECAR_WEB_FACE_ALLOW_WRITES = os.environ.get(
    "RACECAR_WEB_FACE_ALLOW_WRITES", ""
).lower() in ("1", "true", "yes", "on")
'''


SETTINGS_API_PY = '''"""API (REST) face settings. The browsable face: it carries debug_toolbar.

Launched by the api.* vhost (DJANGO_SETTINGS_MODULE=project.settings.api). Only
this face mounts __debug__/ (in project.urls.apiurls), so debug_toolbar's `djdt`
reverse always resolves here; the mcp face never loads it.
"""
# Django settings composition idiom: pull the shared base in, override below.
# pylint: disable=wildcard-import,unused-wildcard-import
from .settings import *  # noqa: F401,F403

FACE = "api"
ROOT_URLCONF = "project.urls.apiurls"

if DEBUG:  # noqa: F405
    INSTALLED_APPS = INSTALLED_APPS + ["debug_toolbar"]  # noqa: F405
    # debug_toolbar middleware goes right after SecurityMiddleware, before the
    # face guard.
    MIDDLEWARE = [
        MIDDLEWARE[0],  # noqa: F405
        "debug_toolbar.middleware.DebugToolbarMiddleware",
        *MIDDLEWARE[1:],  # noqa: F405
    ]
'''


SETTINGS_MCP_PY = '''"""MCP face settings. The machine face: no debug_toolbar, no browsable extras.

Launched by the mcp.* vhost (DJANGO_SETTINGS_MODULE=project.settings.mcp).
"""
# Django settings composition idiom: pull the shared base in, override below.
# pylint: disable=wildcard-import,unused-wildcard-import
from .settings import *  # noqa: F401,F403

FACE = "mcp"
ROOT_URLCONF = "project.urls.mcpurls"
'''


def _urls_api_py(manifest: dict) -> str:
    # The /api/v1/<vertical-path>/ taxonomy lives here, once per vertical, as the
    # include prefix; each vertical's apiurls then route bare command names.
    includes = "\n".join(
        f'    path("{v["http_prefix"]}", include("apps.{v["app"]}.urls.apiurls")),'
        for v in manifest["verticals"]
    )
    return f'''"""REST face urlconf (api process). Mounts each vertical's routes under its
versioned taxonomy prefix /api/v1/<vertical-path>/, plus the OpenAPI document
(/api/v1/openapi.json) and the endpoint sitemap (/sitemap/, /sitemap.xml/)."""
from django.conf import settings
from django.urls import include, path

from project.sitemaps import ApiEndpointSitemap, custom_sitemap
from project.views import openapi

_SITEMAPS = {{"endpoints": ApiEndpointSitemap()}}

urlpatterns = [
    path("api/v1/openapi.json", openapi, name="openapi"),
    path("sitemap.xml/", custom_sitemap, {{"sitemaps": _SITEMAPS}}, name="sitemap_xml"),
    path("sitemap/", custom_sitemap, {{"sitemaps": _SITEMAPS}}, name="sitemap"),
{includes}
]

# debug_toolbar mounts its endpoints only under DEBUG (the house pattern). This
# urlconf is loaded only by the api face, which is where debug_toolbar lives.
if settings.DEBUG and "debug_toolbar" in settings.INSTALLED_APPS:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]
'''


URLS_MCP_PY = '''"""MCP face urlconf (mcp process): the single Streamable-HTTP endpoint."""
from django.urls import path

from apps import mcp

urlpatterns = [
    path("mcp", mcp.endpoint, name="mcp"),
    path("mcp/", mcp.endpoint),
]
'''

# --------------------------------------------------------------------------
# per-vertical app (apps/<name>/) — both faces over its own api, vertical-first
# --------------------------------------------------------------------------

APP_CONFIG_PY = '''from django.apps import AppConfig


class {cls}(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "{name}"
'''

EMPTY_MODELS_PY = '''"""Database-light: this face holds no models."""
'''

EMPTY_ADMIN_PY = '''"""Database-light: nothing registered with the admin."""
'''


def _commands_registry(vertical: dict) -> str:
    """The COMMANDS dict body. `route` is the bare command name; the versioned
    /api/v1/<vertical-path>/ prefix is applied by project/urls/apiurls.py."""
    rows = []
    for c in vertical["commands"]:
        rows.append(
            f'    "{c["subcommand"]}": {{\n'
            f'        "tool": "{c["mcp_tool"]}",\n'
            f'        "func": {c["api_callable"]},\n'
            f'        "schema": {c["input_schema"]!r},\n'
            f'        "write": {c["is_write"]},\n'
            f'        "method": "{c["method"].upper()}",\n'
            f'        "route": "{c["route"]}",\n'
            f'        "description": {c["description"]!r},\n'
            f"    }},"
        )
    return "COMMANDS = {\n" + "\n".join(rows) + "\n}\n"


def _commands_py(vertical: dict) -> str:
    """apps/<v>/commands.py: the transport-neutral binding over the vertical's api.
    The single home for the command table; both faces import COMMANDS from here."""
    imports = "\n".join(
        f"from {vertical['api_module']} import {name}"
        for name in dict.fromkeys(c["api_callable"] for c in vertical["commands"])
    )
    registry = _commands_registry(vertical)
    return f'''"""Command bindings for the {vertical["vertical"]} vertical -- the transport-neutral
table over its api. One home for the binding: apiviews (REST) and mcpviews (MCP)
both import COMMANDS from here, so neither face derives from the other and the
schema is written once per command.
"""
# COMMANDS embeds api-authored descriptions as string literals; black cannot wrap a
# single string token, so a long description may exceed the line length. Generated
# data, not hand-formatted code.
# pylint: disable=line-too-long
{imports}

{registry}'''


def _apiviews_py(vertical: dict) -> str:
    """apps/<v>/views/apiviews.py: REST views, thin async adapters built from COMMANDS."""
    return f'''"""REST views for the {vertical["vertical"]} vertical -- thin async adapters over its
api, built from the vertical's COMMANDS binding. Each coerces transport input, calls
the api callable off the event loop, and renders JSON.
"""
import json

from asgiref.sync import sync_to_async
from django.conf import settings
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from ..commands import COMMANDS


def _err(message, status_code):
    return JsonResponse({{"error": message}}, status=status_code)


def _coerce_query(schema, query):
    out = {{}}
    for key, spec in schema.get("properties", {{}}).items():
        if key not in query and not query.getlist(key):
            continue
        kind = spec.get("type")
        if kind == "boolean":
            out[key] = query.get(key, "").lower() in ("1", "true", "yes", "on")
        elif kind == "integer":
            out[key] = int(query.get(key))
        elif kind == "number":
            out[key] = float(query.get(key))
        elif kind == "array":
            out[key] = query.getlist(key) or query.get(key, "").split(",")
        else:
            out[key] = query.get(key)
    return out


def _make_view(spec):
    schema = spec["schema"]

    @csrf_exempt
    async def _view(request):
        if request.method != spec["method"]:
            return _err("method not allowed", 405)
        if spec["write"] and not settings.RACECAR_WEB_FACE_ALLOW_WRITES:
            return _err("writes disabled; set RACECAR_WEB_FACE_ALLOW_WRITES=1", 403)
        if request.method == "GET":
            kwargs = _coerce_query(schema, request.GET)
        else:
            try:
                kwargs = json.loads(request.body or b"{{}}")
            except json.JSONDecodeError:
                return _err("invalid JSON body", 400)
            if not isinstance(kwargs, dict):
                return _err("body must be a JSON object", 400)
        missing = [r for r in schema.get("required", []) if r not in kwargs or kwargs[r] is None]
        if missing:
            return _err(f"missing required: {{missing}}", 400)
        try:
            result = await sync_to_async(spec["func"], thread_sensitive=False)(**kwargs)
        except ValueError as exc:  # api caller-input error
            return _err(str(exc), 400)
        return JsonResponse(result, safe=not isinstance(result, list))

    return _view


VIEWS = {{name: _make_view(spec) for name, spec in COMMANDS.items()}}
'''


def _mcpviews_py(vertical: dict) -> str:
    """apps/<v>/views/mcpviews.py: the MCP projection of COMMANDS, keyed by tool name."""
    return f'''"""MCP tool specs for the {vertical["vertical"]} vertical: the MCP
projection of its COMMANDS binding, keyed by tool name. apps/mcp.py aggregates
every vertical's TOOLS into the single endpoint.
"""
from ..commands import COMMANDS

TOOLS = {{spec["tool"]: spec for spec in COMMANDS.values()}}
'''


def _apiurls_py(vertical: dict) -> str:
    """apps/<v>/urls/apiurls.py: bare command routes (the versioned prefix is in
    project/urls/apiurls.py)."""
    return f'''"""REST routes for the {vertical["vertical"]} vertical, built from COMMANDS. The
versioned /api/v1/<vertical-path>/ prefix is added by project/urls/apiurls.py."""
from django.urls import path

from ..commands import COMMANDS
from ..views.apiviews import VIEWS

urlpatterns = [
    path(spec["route"], VIEWS[name], name=spec["tool"]) for name, spec in COMMANDS.items()
]
'''


# --------------------------------------------------------------------------
# apps/mcp.py — the single MCP endpoint, aggregating every vertical's mcpviews
# --------------------------------------------------------------------------


def _mcp_endpoint_py(manifest: dict) -> str:
    """apps/mcp.py: one Streamable-HTTP endpoint. Imports each vertical's TOOLS
    (apps/mcp.py -> apps/<v>/views/mcpviews; the verticals never import back)."""
    imports = "\n".join(
        f"from apps.{v['app']}.views.mcpviews import TOOLS as _{v['app']}_tools"
        for v in manifest["verticals"]
    )
    agg = ", ".join(f"_{v['app']}_tools" for v in manifest["verticals"])
    return f'''"""MCP face: one Streamable-HTTP endpoint exposing every vertical's tools. It
aggregates each vertical's TOOLS (apps/mcp.py -> apps/<v>/views/mcpviews; the
verticals never import back). Tools-only, request/response: every POST gets
application/json; GET -> 405. Wire shapes per MCP revision {manifest["mcp_protocol_version"]}.
"""
import json

from asgiref.sync import sync_to_async
from django.conf import settings
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt

{imports}

PROTOCOL_VERSION = "{manifest["mcp_protocol_version"]}"

# tool name -> spec (func, schema, write, description). Each vertical's mcpviews
# already keys its TOOLS by tool name; this unions them.
_TOOLS = {{}}
for _tools in ({agg},):
    _TOOLS.update(_tools)


def _result(req_id, result):
    return JsonResponse({{"jsonrpc": "2.0", "id": req_id, "result": result}})


def _error(req_id, code, message):
    return JsonResponse(
        {{"jsonrpc": "2.0", "id": req_id, "error": {{"code": code, "message": message}}}}
    )


def _tool_result(req_id, text, is_error):
    content = [{{"type": "text", "text": text}}]
    return _result(req_id, {{"content": content, "isError": is_error}})


def _tool_list():
    tools = []
    for name, spec in _TOOLS.items():
        tools.append(
            {{
                "name": name,
                "description": spec["description"] or name,
                "inputSchema": spec["schema"],
                "annotations": {{"readOnlyHint": not spec["write"]}},
            }}
        )
    return {{"tools": tools}}


async def _tool_call(req_id, params):
    name = (params or {{}}).get("name")
    spec = _TOOLS.get(name)
    if spec is None:
        return _error(req_id, -32602, f"Unknown tool: {{name}}")
    if spec["write"] and not settings.RACECAR_WEB_FACE_ALLOW_WRITES:
        return _tool_result(req_id, "writes disabled; set RACECAR_WEB_FACE_ALLOW_WRITES=1", True)
    arguments = (params or {{}}).get("arguments") or {{}}
    try:
        result = await sync_to_async(spec["func"], thread_sensitive=False)(**arguments)
    except ValueError as exc:
        return _tool_result(req_id, str(exc), True)
    return _tool_result(req_id, json.dumps(result, default=str), False)


@csrf_exempt
async def endpoint(request):
    """The single MCP Streamable-HTTP endpoint: dispatch one JSON-RPC message."""
    if request.method != "POST":
        return JsonResponse({{"error": "method not allowed"}}, status=405)
    try:
        msg = json.loads(request.body or b"{{}}")
    except json.JSONDecodeError:
        return _error(None, -32700, "Parse error")
    method, req_id = msg.get("method"), msg.get("id")
    if req_id is None and method and method.startswith("notifications/"):
        return HttpResponse(status=202)
    if method == "initialize":
        return _result(
            req_id,
            {{
                "protocolVersion": PROTOCOL_VERSION,
                "capabilities": {{"tools": {{"listChanged": False}}}},
                "serverInfo": {{"name": "{manifest["package"]}-mcp", "version": "0.1.0"}},
            }},
        )
    if method == "tools/list":
        return _result(req_id, _tool_list())
    if method == "tools/call":
        return await _tool_call(req_id, msg.get("params"))
    return _error(req_id, -32601, f"Method not found: {{method}}")
'''

# --------------------------------------------------------------------------
# api-face docs + sitemap — all derived from the one manifest
# --------------------------------------------------------------------------


def _openapi_doc(manifest: dict) -> str:
    """OpenAPI 3.1 document for the REST face, built from the manifest. GET commands
    expose query parameters; non-GET commands take the input_schema as a JSON body."""
    paths: dict = {}
    tags = []
    seen = set()
    for v in manifest["verticals"]:
        tag = v["app"]
        if tag not in seen:
            seen.add(tag)
            tags.append({"name": tag, "description": f"{v['vertical']} endpoints"})
        for c in v["commands"]:
            method = c["method"].lower()
            schema = c["input_schema"]
            op = {
                "operationId": c["mcp_tool"],
                "summary": c["description"] or c["subcommand"],
                "tags": [tag],
                "responses": {"200": {"description": "Success"}},
            }
            if c["is_write"]:
                op["responses"]["403"] = {
                    "description": "Writes disabled (RACECAR_WEB_FACE_ALLOW_WRITES off)"
                }
            if method == "get":
                props = schema.get("properties", {})
                required = set(schema.get("required", []))
                op["parameters"] = [
                    {"name": k, "in": "query", "required": k in required, "schema": s}
                    for k, s in props.items()
                ]
            else:
                op["requestBody"] = {
                    "required": bool(schema.get("required")),
                    "content": {"application/json": {"schema": schema}},
                }
            paths.setdefault(c["http_path"], {})[method] = op
    doc = {
        "openapi": "3.1.0",
        "info": {
            "title": f"{manifest['package']} REST API",
            "version": "1.0.0",
            "description": (
                "Generated by racecar-deploy. All routes are under /api/v1/. Write "
                "verbs (any non-GET) are gated by RACECAR_WEB_FACE_ALLOW_WRITES and "
                "return 403 when off. The MCP face is a separate server at /mcp."
            ),
        },
        "servers": [{"url": "/", "description": "This host"}],
        "tags": tags,
        "paths": paths,
    }
    return json.dumps(doc, indent=2) + "\n"


def _endpoints_md(manifest: dict) -> str:
    """Human + LLM endpoint list: the REST routes and the MCP tools, one table each."""
    rest, mcp = [], []
    for v in manifest["verticals"]:
        for c in v["commands"]:
            rest.append(
                f'| {c["method"].upper()} | `{c["http_path"]}` | '
                f'{"yes" if c["is_write"] else "no"} | {c["description"]} |'
            )
            mcp.append(
                f'| `{c["mcp_tool"]}` | {"no" if c["is_write"] else "yes"} | {c["description"]} |'
            )
    rest_tbl = "\n".join(rest)
    mcp_tbl = "\n".join(mcp)
    return f'''# {manifest["package"]} web face — endpoints

Generated by racecar-deploy from the Interface Manifest. Two faces over the same
`api`: REST on `api.*` (host-routed), MCP on `mcp.*`. Machine spec:
[`openapi.json`](openapi.json).

## REST endpoints (`/api/v1/<vertical-path>/<command>`)

| Method | Path | Write | Description |
|---|---|---|---|
{rest_tbl}

The OpenAPI document is served at `/api/v1/openapi.json`; the crawlable GET
surface is listed at `/sitemap/` and `/sitemap.xml/`.

## MCP tools (one Streamable-HTTP server at `/mcp`)

| Tool | Read-only | Description |
|---|---|---|
{mcp_tbl}

Write verbs (any non-GET / non-read-only) are refused unless
`RACECAR_WEB_FACE_ALLOW_WRITES=1`.
'''


def _sitemaps_py(manifest: dict) -> str:
    """project/sitemaps.py: a sitemap of the REST GET endpoints (house pattern)."""
    get_paths = [
        c["http_path"]
        for v in manifest["verticals"]
        for c in v["commands"]
        if c["method"].upper() == "GET"
    ]
    paths_block = "\n".join(f'    "{p}",' for p in get_paths)
    return f'''"""Sitemap of the REST API's GET endpoints (house pattern, a-la eninesites). The
domain comes from the request host via get_domain, so no django.contrib.sites
dependency is needed.
"""
from django.contrib.sitemaps import Sitemap
from django.contrib.sitemaps.views import sitemap as _sitemap_view

# Generated: the GET endpoints of the REST face (the crawlable surface).
GET_ENDPOINTS = [
{paths_block}
]


def custom_sitemap(request, sitemaps):
    """Attach the request to each sitemap, then delegate to Django's sitemap view."""
    for _sm in sitemaps.values():
        _sm.request = request
    return _sitemap_view(request, sitemaps)


class ApiEndpointSitemap(Sitemap):
    """The REST GET endpoints. Host comes from the request, not contrib.sites."""

    request = None
    changefreq = "weekly"
    priority = 0.5

    def get_domain(self, site=None):
        """Use the request host instead of the Sites framework."""
        if self.request is not None:
            return self.request.get_host()
        return super().get_domain(site)

    def items(self):
        """The GET endpoint paths."""
        return GET_ENDPOINTS

    def location(self, item):
        """The endpoint path, already absolute from the server root."""
        return item
'''


# --------------------------------------------------------------------------
# non-python file bodies
# --------------------------------------------------------------------------

PYPROJECT_TOML = """# Generated djapp pyproject (pypkg+djapp). No [project] / [build-system]:
# the djapp runs via manage.py / asgi.py and is not a wheel.
[dependency-groups]
runtime = [
    "django>=6.0",
    "uvicorn>=0.30",
]
"""

APACHE_API_VHOST = """# Generated: REST face vhost. Apache terminates TLS + reverse-proxies to ASGI.
<VirtualHost *:443>
    ServerName api.example.com
    ProxyPreserveHost On
    ProxyPass        / http://127.0.0.1:8001/
    ProxyPassReverse / http://127.0.0.1:8001/
</VirtualHost>
"""

APACHE_MCP_VHOST = """# Generated: MCP face vhost. Own ASGI process on :8002 (project.settings.mcp).
<VirtualHost *:443>
    ServerName mcp.example.com
    ProxyPreserveHost On
    ProxyPass        / http://127.0.0.1:8002/
    ProxyPassReverse / http://127.0.0.1:8002/
</VirtualHost>
"""

RUN_SH = """#!/usr/bin/env bash
# Local flight: two processes, one per face (mirrors the two-vhost deploy).
# REST on :8001 (project.settings.api), MCP on :8002 (project.settings.mcp).
set -euo pipefail
cd "$(dirname "$0")"
DJANGO_SETTINGS_MODULE=project.settings.api uvicorn project.asgi:application \\
    --host 127.0.0.1 --port 8001 "$@" &
api_pid=$!
DJANGO_SETTINGS_MODULE=project.settings.mcp uvicorn project.asgi:application \\
    --host 127.0.0.1 --port 8002 "$@" &
mcp_pid=$!
trap 'kill $api_pid $mcp_pid 2>/dev/null' EXIT
wait
"""


# --------------------------------------------------------------------------
# renderer
# --------------------------------------------------------------------------


def _app_class(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_")) + "Config"


def render_project(manifest: dict, out: Path, *, manifest_only: bool = False) -> None:
    """Write the qjango-shaped djapp tree: project/ + apps/<v>/ + apps/mcp.py."""
    (out / "project").mkdir(parents=True, exist_ok=True)
    # docs/api/ holds the generated artifacts: the manifest IR (also what
    # --manifest-only emits), the OpenAPI doc, and the human/LLM endpoint list.
    docs_api = out / "docs" / "api"
    docs_api.mkdir(parents=True, exist_ok=True)
    (docs_api / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    if manifest_only:
        return

    # project/ (composition root)
    proj = out / "project"
    (proj / "__init__.py").write_text("")
    # settings/ package: shared base + one module per face
    settings_pkg = proj / "settings"
    settings_pkg.mkdir(parents=True, exist_ok=True)
    (settings_pkg / "__init__.py").write_text("")
    (settings_pkg / "settings.py").write_text(_settings_py(manifest))
    (settings_pkg / "api.py").write_text(SETTINGS_API_PY)
    (settings_pkg / "mcp.py").write_text(SETTINGS_MCP_PY)
    # urls/ package: one urlconf per face (selected by each settings module)
    urls_pkg = proj / "urls"
    urls_pkg.mkdir(parents=True, exist_ok=True)
    (urls_pkg / "__init__.py").write_text("")
    (urls_pkg / "apiurls.py").write_text(_urls_api_py(manifest))
    (urls_pkg / "mcpurls.py").write_text(URLS_MCP_PY)
    (proj / "faceguard.py").write_text(FACEGUARD_PY)
    (proj / "asgi.py").write_text(ASGI_PY)
    (proj / "wsgi.py").write_text(WSGI_PY)
    (proj / "views.py").write_text(VIEWS_PY)
    (proj / "sitemaps.py").write_text(_sitemaps_py(manifest))

    # apps/<vertical>/ (one Django app per vertical; both faces co-located)
    for v in manifest["verticals"]:
        app = out / "apps" / v["app"]
        (app / "views").mkdir(parents=True, exist_ok=True)
        (app / "urls").mkdir(parents=True, exist_ok=True)
        (app / "__init__.py").write_text("")
        (app / "apps.py").write_text(
            APP_CONFIG_PY.format(cls=_app_class(v["app"]), name=f"apps.{v['app']}")
        )
        (app / "models.py").write_text(EMPTY_MODELS_PY)
        (app / "admin.py").write_text(EMPTY_ADMIN_PY)
        (app / "commands.py").write_text(_commands_py(v))
        (app / "views" / "__init__.py").write_text("")
        (app / "views" / "apiviews.py").write_text(_apiviews_py(v))
        (app / "views" / "mcpviews.py").write_text(_mcpviews_py(v))
        (app / "urls" / "__init__.py").write_text("")
        (app / "urls" / "apiurls.py").write_text(_apiurls_py(v))
    (out / "apps" / "__init__.py").write_text("")

    # apps/mcp.py — the single MCP endpoint, aggregating every vertical's mcpviews
    (out / "apps" / "mcp.py").write_text(_mcp_endpoint_py(manifest))

    # docs/api/ — the OpenAPI spec + the human/LLM endpoint list (api face).
    # docs_api was created (with manifest.json) at the top of render_project.
    (docs_api / "openapi.json").write_text(_openapi_doc(manifest))
    (docs_api / "ENDPOINTS.md").write_text(_endpoints_md(manifest))

    # top-level files
    (out / "manage.py").write_text(MANAGE_PY)
    (out / "pyproject.toml").write_text(PYPROJECT_TOML)
    (out / "run.sh").write_text(RUN_SH)
    (out / "run.sh").chmod(0o755)
    apache = out / "apache"
    apache.mkdir(parents=True, exist_ok=True)
    (apache / "api.vhost.conf").write_text(APACHE_API_VHOST)
    (apache / "mcp.vhost.conf").write_text(APACHE_MCP_VHOST)
